[general]
live_config_reload = true
import = [
    "~/.config/alacritty/themes/themes/gruvbox_light.toml"
]

# [colors.primary]
# background = "#000000"

[font]
size = 10.0
# offset = { y = 50 }

[font.bold]
family = "Iosevka Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Iosevka Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Iosevka Nerd Font"
style = "Light Italic"

[font.normal]
family = "Iosevka Nerd Font"
style = "Regular"

[keyboard]
bindings = [
  { key = "N", mods = "Control", action = "SpawnNewInstance" },
  { key = "T", mods = "Command|Shift", chars = "RAILS_ENV=test bundle exec rake spec SPEC=spec/" },
  { key = "Y", mods = "Control|Shift", command = { program = "/opt/homebrew/bin/bash", args = ["-c", "/Users/tomm/bin/ts"] } },
]

[terminal.shell]
args = ["--login"]
program = "/opt/homebrew/bin/fish"
# program = "/opt/homebrew/bin/bash"

[window]
startup_mode = "Maximized"

[window.dimensions]
columns = 100
lines = 240


[terminal]

