#!/bin/bash

function set_theme() {
  local theme="${1:-}"
  cp $HOME/dev/dotfiles/termux/gruvbox-${theme}.properties $HOME/.termux/colors.properties
  echo "Reloading Settings..."
  am broadcast --user 0 -a com.termux.app.reload_style com.termux > /dev/null
  export TERMUX_THEME="${theme}"
}
