#!/bin/bash

case ${1} in
  "plan")  shift; cmd="terraform init && terraform plan -parallelism=100 ${@}";;
  "apply") shift; cmd="terraform init && terraform apply -auto-approve -parallelism=100 ${@}";;
  "dns")   cmd="grep fqdn terraform.tfstate | awk '{print \$2}' | tr -d '\"' | tr -d ','";;
  "ls")    cmd="terraform show | grep -E '^[a-zA-Z]' | tr -d ':'";;
  "sg")    cmd="grep -E '\"sg-(.*)' terraform.tfstate | awk '{print \$2}' | sort -u | tr -d '\"' | tr -d ','";;
  *)       cmd="terraform ${@}";;
esac
echo $cmd
eval $cmd

