alias sort="LC_ALL=C sort" # Makes GNU sort _much_ faster
alias grep="grep --color"  # Enable grep colours
alias g="git"
alias pip="python -m pip"
alias j="cat ${1} | jq ."
alias shuf="gshuf"
alias sed="gsed"

