#!/bin/bash

export CLICOLOR="exfxcxdxbxegedabagacad" # enable colours in OSX bash

alias grep="grep --color=auto" # Enable grep colours
alias ls="ls --color" # Enable GNU ls colours
alias g="git"
alias v="vim"

# Just alias gnu variants over BSD default utilities
alias shuf="gshuf"
alias readlink="greadlink"
alias sed="gsed"
alias tr="gtr"
alias sort="LC_ALL=C gsort" # Makes GNU sort much faster
alias bmon="bmon -p en0 -o 'curses:bgchar= '"
alias gpurge="git fetch origin --prune && git branch --merged | grep -v master | xargs git branch -d"

# Some nice helpers & shortcuts
alias j="cat ${1} | jq ."

if [ -f ~/.aws/credentials ] && [ "$(head -n 1 ~/.aws/credentials)" == "[default]" ]; then
  # This sed methods yields ~20x faster load times than using `aws configure`
  export AWS_ACCESS_KEY_ID="$(sed '2q;d' ~/.aws/credentials | cut -d ' ' -f 3)"
  export AWS_SECRET_ACCESS_KEY="$(sed '4q;d' ~/.aws/credentials | cut -d ' ' -f 3)"
fi

