# Exit if we are a login shell, and ~/.bash_profile has already been sourced.
$(shopt -q login_shell) && [ ! -z "${BASH_PROFILE_SOURCED:-}" ] && return 0
echo -e "~~ login shell\n"

# Link Homebrew installs in $HOME/bin
[ -d /usr/local/bin ] && PATH="/usr/local/bin:$PATH"

export PYENV_ROOT="$HOME/.pyenv"
export PYTHONPATH="$PYENV_ROOT:$HOME/python-pkgs/lib/python/"

PATH="$PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH"       # Add python bins & shims under PYENV_ROOT
PATH="$HOME/.rvm/bin:$PATH"  n                       # Add rvm binaries
PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH" # Ensure that GNU utils are used over BSD
PATH="/Library/Frameworks/Python.framework/Versions/3.8/bin:${PATH}"

export PATH

# Load Ruby Version Manager & pyenv
[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm"
command -v pyenv 1>/dev/null 2>&1 && eval "$(pyenv init -)"

export BASH_PROFILE_SOURCED="true"
source "$HOME/.bashrc"

