#!/bin/bash

export CLICOLOR="exfxcxdxbxegedabagacad" # enable colours in OSX bash

alias grep="grep --color=auto" # Enable grep colours
alias g="git"
alias v="vim"

# Just alias gnu variants over BSD default utilities
alias shuf="gshuf"
alias sed="gsed"
alias tr="gtr"
alias sort="LC_ALL=C gsort" # Makes GNU sort much faster

# Some nice helpers & shortcuts
alias j="cat ${1} | jq ."

# If set up as default by awscli, then the credentials file should begin with
# defaults, in this order.
#
# [default]
# aws_access_key_id = XXXX
# region = some-region-3
# aws_secret_access_key = XXXX
if [[ -f ~/.aws/credentials ]] && [[ $(head -n 1 ~/.bashrc) == "[default]" ]]; then
  # This sed methods yields ~20x faster load times than using `aws configure`
  export AWS_ACCESS_KEY_ID="$(sed '2q;d' ~/.aws/credentials | cut -d ' ' -f 3)"
  export AWS_SECRET_ACCESS_KEY="$(sed '4q;d' ~/.aws/credentials | cut -d ' ' -f 3)"
fi

