alias g="git"
alias j="cat ${1} | jq ."
alias v="vim"

alias pip="python3 -m pip"
alias python="python3"

alias ls="ls --color=auto"
alias sort="LC_ALL=C sort" # Makes GNU sort _much_ faster
alias grep="grep --color"  # Enable grep colours
