alias sort="LC_ALL=C sort" # Makes GNU sort _much_ faster
alias grep="grep --color"  # Enable grep colours
alias g="git"
# alias ls="ls --color=auto"
# alias redshift="redshift -l 37.7490:144.9120"
alias pip="python -m pip"
# alias ls="ls --color=auto"
alias j="cat ${1} | jq ."
alias sed="gsed"
alias python="python3"
export PTV_USER_ID="3000972"
export PTV_API_KEY="34fba7f6-43c3-493b-8fea-cd89df1dbfa1"
