# Exit if we are a login shell, and ~/.bash_profile has already been sourced.
if ! $(shopt -q login_shell); then
  echo "~~ non-login shell, exiting"
  return 0
else
  if [ "${BASH_PROFILE_SOURCED:-}" == "true" ]; then
    source ~/.bashrc
    return 0
  fi
fi
echo "~~ sourcing .bash_profile"

# Load personal scripts
PATH="$HOME/bin/:$HOME/.local/bin:$PATH"

# Set up rustup
PATH="$HOME/.cargo/bin:$PATH"

# Set up go
export GOPATH=$HOME/go
export GOROOT=/usr/local/go
PATH=$PATH:$GOPATH/bin:$GOROOT/bin

alias crontab="VIM_CRONTAB=true crontab"
export EDITOR=vim
export VISUAL=vim

# Enable bash completion
[[ -r "/usr/local/etc/profile.d/bash_completion.sh" ]] && . "/usr/local/etc/profile.d/bash_completion.sh"
. $HOME/dev/alacritty/extra/completions/alacritty.bash

# Setup kitty
source <(kitty + complete setup bash)
KITTY_CONFIG_DIRECTORY="$HOME/.config/kitty/"

# Export final path & other important vars
export PATH
export TERM=xterm-256color

export BASH_PROFILE_SOURCED="true"

# Load tmux once before entering .bashrc, ensure that we're not already in tmux
[ $TMUX ] || tmux -2

[ -f "$HOME/.bashrc" ] && source ~/.bashrc

export PATH="$HOME/.cargo/bin:$PATH"
