[general]
live_config_reload = true
import = [
    # "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
    "~/.config/alacritty/font-ansi.toml",
    "~/.config/alacritty/themes/ansilove.toml",
]

[keyboard]
bindings = [
  { key = "N", mods = "Control", action = "SpawnNewInstance" },
  { key = "T", mods = "Command|Shift", chars = "RAILS_ENV=test bundle exec rake spec SPEC=spec/" },
  { key = "Y", mods = "Control|Shift", command = { program = "/opt/homebrew/bin/bash", args = ["-c", "/Users/tomm/bin/ts 2>&1 > /Users/tomm/bin/ts.log"] } },
]

[terminal.shell]
args = ["--login"]
program = "/bin/bash"
# program = "/opt/homebrew/bin/fish"
# program = "/opt/homebrew/bin/bash"

[window]
startup_mode = "Maximized"

[window.dimensions]
columns = 100
lines = 240


[terminal]

[env]
WINIT_X11_SCALE_FACTOR='1.0'
